# Development profile config

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/sensors
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Log levels
logging.level.root=INFO
logging.level.com.project.weathermetrics=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

# Tracing
management.tracing.sampling.probability=1.0
