# Common configuration
spring.application.name=weather-metrics-api

# Jackson JSON serialization
spring.jackson.serialization.write-dates-as-timestamps=false

# Default active profile
spring.profiles.active=dev

# Weather API Configuration
weather.api.key=f9fc597ed5025be24eb9284eeee858c7
weather.api.city=Dublin, IE

#Log Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId:-}] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId:-}] %logger{36} - %msg%n

#File Logging
logging.file.name=logs/weather-metrics-api.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=100MB
logging.logback.rollingpolicy.file-name-pattern=logs/weather-metrics-api-%d{yyyy-MM-dd}.%i.log


spring.mvc.log.resolved-exception=false
